reupload used keys

diff --git a/.github/workflows/multi_allocations.yml b/.github/workflows/multi_allocations.yml
--- a/.github/workflows/multi_allocations.yml
+++ b/.github/workflows/multi_allocations.yml
@@ -78,7 +78,6 @@ jobs:
           yagna service run&
           sleep 4
           yagna id create --password= --from-private-key=$(cat ../../downloaded_private_key_0.key) identity0
-          rm ../../downloaded_private_key_0.key
           yagna app-key create --id identity0 dev_req | sed 's/^/\YAGNA_REQUESTOR_APPKEY=/' >> $GITHUB_ENV
           echo YAGNA_ACCOUNT_0=$(yagna id show identity0 | grep -oP '(?<=nodeId: )[^\s]+') >> $GITHUB_ENV
 
@@ -87,7 +86,6 @@ jobs:
         run: |
           cd golem/requestor
           echo "YAGNA_AUTOCONF_ID_SECRET=$(cat ../../downloaded_private_key_0.key)" >> .env
-          rm ../../downloaded_private_key_0.key
           yagna service run&
           sleep 4
           yagna app-key create dev_req | sed 's/^/\YAGNA_REQUESTOR_APPKEY=/' >> $GITHUB_ENV
@@ -233,3 +231,11 @@ jobs:
         with:
           name: data_${{ matrix.id }}.tar.zst
           path: data_${{ matrix.id }}.tar.zst
+
+      - name: Upload used private key back to the server
+        if: always()
+        run: |
+          grep -qE '^[a-fA-F0-9]{64}$' downloaded_private_key_0.key || { echo "Error: File contents do not match expected format: $(cat downloaded_private_key_0.key)"; exit 1; }
+          curl -sSL -H "Authorization: Bearer ${{ secrets.PRIVATE_KEY_SERVER_KEY }}" -d $(cat downloaded_private_key_0.key) https://polygongas.org/keys/add/used_accounts
+          grep -qE '^[a-fA-F0-9]{64}$' downloaded_private_key_1.key || { echo "Error: File contents do not match expected format: $(cat downloaded_private_key_0.key)"; exit 1; }
+          curl -sSL -H "Authorization: Bearer ${{ secrets.PRIVATE_KEY_SERVER_KEY }}" -d $(cat downloaded_private_key_1.key) https://polygongas.org/keys/add/used_accounts
