Enable integration tests for new payment system

diff --git a/.github/workflows/multi_allocations.yml b/.github/workflows/multi_allocations.yml
--- a/.github/workflows/multi_allocations.yml
+++ b/.github/workflows/multi_allocations.yml
@@ -1,4 +1,4 @@
-name: Test with assets
+name: Multi allocations
 on:
   push:
     branches: [ "main" ]
@@ -6,20 +6,30 @@ on:
     branches: [ "main" ]
 
 jobs:
-  run_test:
+  multi-allocations:
     strategy:
       fail-fast: false
       matrix:
         include:
-          - restart: true
-            one_account: false
-            interval: 2m
-            id: 0
-
           - restart: false
             one_account: true
             interval: 1m
+            id: 0
+
+          - restart: true
+            one_account: false
+            interval: 2m
             id: 1
+
+          - restart: false
+            one_account: true
+            interval: 5m
+            id: 2
+
+          - restart: false
+            one_account: true
+            interval: 10m
+            id: 3
 
     timeout-minutes: 20
     runs-on: ubuntu-latest
@@ -45,13 +55,21 @@ jobs:
         run: |
           python advanced/prepare_runtime.py --mode central --payments full
 
-      - name: Download private key
+      - name: Download private key 0
         run: |
           set -x
           curl -sSL -H "Authorization: Bearer ${{ secrets.PRIVATE_KEY_SERVER_KEY }}" https://polygongas.org/keys/get/unused_accounts > downloaded_private_key_0.key
           echo "Keys left $(curl -sSL https://polygongas.org/keys/count/unused_accounts)"
           # Check if the downloaded key is a valid private key
           grep -qE '^[a-fA-F0-9]{64}$' downloaded_private_key_0.key || { echo "Error: File contents do not match expected format: $(cat downloaded_private_key_0.key)"; exit 1; }
+
+      - name: Download private key 1
+        run: |
+          set -x
+          curl -sSL -H "Authorization: Bearer ${{ secrets.PRIVATE_KEY_SERVER_KEY }}" https://polygongas.org/keys/get/unused_accounts > downloaded_private_key_1.key
+          echo "Keys left $(curl -sSL https://polygongas.org/keys/count/unused_accounts)"
+          # Check if the downloaded key is a valid private key
+          grep -qE '^[a-fA-F0-9]{64}$' downloaded_private_key_1.key || { echo "Error: File contents do not match expected format: $(cat downloaded_private_key_1.key)"; exit 1; }
 
       - name: Run requestor second account
         if: matrix.one_account != true
@@ -106,14 +124,16 @@ jobs:
 
       - name: Run debit note test
         run: |
-          cd examples/debitnotetest
-          echo "EXAMPLE_STEPS=2" >> .env
+          cd examples/multi-allocation-double-activity
+          echo "FUNDER_PRIVATE_KEY=0x$(cat ../../downloaded_private_key_1.key)" >> .env
+          echo "SPENDER_ADDRESS=$YAGNA_ACCOUNT_0" >> .env
           npm install --silent
-          npm run run&
+          node index.mjs
 
       - name: Wait for payments
         run: |
           cd reports
+          
           npm install --silent
           node wait_for_payments.js
         env:
@@ -217,3 +237,5 @@ jobs:
         run: |
           grep -qE '^[a-fA-F0-9]{64}$' downloaded_private_key_0.key || { echo "Error: File contents do not match expected format: $(cat downloaded_private_key_0.key)"; exit 1; }
           curl -sSL -H "Authorization: Bearer ${{ secrets.PRIVATE_KEY_SERVER_KEY }}" -d $(cat downloaded_private_key_0.key) https://polygongas.org/keys/add/used_accounts
+          grep -qE '^[a-fA-F0-9]{64}$' downloaded_private_key_1.key || { echo "Error: File contents do not match expected format: $(cat downloaded_private_key_0.key)"; exit 1; }
+          curl -sSL -H "Authorization: Bearer ${{ secrets.PRIVATE_KEY_SERVER_KEY }}" -d $(cat downloaded_private_key_1.key) https://polygongas.org/keys/add/used_accounts
