work on tests

diff --git a/.github/workflows/test_with_assets.yml b/.github/workflows/test_with_assets.yml
--- a/.github/workflows/test_with_assets.yml
+++ b/.github/workflows/test_with_assets.yml
@@ -34,8 +34,8 @@ jobs:
 
       - name: Download private key
         run: |
-          curl -sSL -H "Authorization: Bearer ${{ secrets.PRIVATE_KEY_SERVER_KEY }}" https://polygongas.org/keys/get | tee downloaded_private_key_0.key
-          grep -qE '^[a-fA-F0-9]{63}$' downloaded_private_key_0.key || exit 1
+          curl -sSL -H "Authorization: Bearer ${{ secrets.PRIVATE_KEY_SERVER_KEY }}" https://polygongas.org/keys/get > downloaded_private_key_0.key
+          grep -qE '^[a-fA-F0-9]{63}$' downloaded_private_key_0.key || { echo "Error: File contents do not match expected format"; cat downloaded_private_key_0.key; exit 1; }
           echo "Keys left $(curl -sSL https://polygongas.org/keys/count)"
 
       - name: Run requestor
